services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: promptforge-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "5432:5432"
    networks:
      - promptforge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U promptforge -d promptforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: promptforge-backend
    env_file:
      - .env
    environment:
      DB_HOST: database
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - promptforge-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promptforge-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - promptforge-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  promptforge-network:
    driver: bridge